name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ECR_REPOSITORY: dev-labs/mcp-server
  IMAGE_TAG: cloudwatch-tracker

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@Juri-Dev-Lab"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JURI_PACKAGES_TOKEN }}

      - name: Run tests
        run: npm test

      - name: Run linting
        run: npm run lint

      - name: Build package
        run: npm run build

      - name: Create .env file
        run: echo "${{ secrets.ENV_LIVE }}" > .env

  publish-npm:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@Juri-Dev-Lab"

      - name: Check npm configuration
        run: |
          echo "NPM registry configuration:"
          npm config list
          echo "Creating .npmrc with token"
          echo "@Juri-Dev-Lab:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.JURI_PACKAGES_TOKEN }}" >> .npmrc
          echo "Current directory content:"
          ls -la

      - name: Bump patch version
        run: npm version patch --no-git-tag-version
        # 또는 minor나 major 버전을 올리려면:
        # run: npm version minor --no-git-tag-version

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JURI_PACKAGES_TOKEN }} #repo, package:read, package:write

      - name: Build package
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JURI_PACKAGES_TOKEN }} #repo, package:read, package:write

  publish-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@Juri-Dev-Lab"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker용 .npmrc 파일 생성
        run: |
          echo "@Juri-Dev-Lab:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.JURI_PACKAGES_TOKEN }}" >> .npmrc

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          secret-files: |
            "npmrc=.npmrc"
          tags: |
            devthorjuri/mcp-cloudwatch-tracker:latest
            devthorjuri/mcp-cloudwatch-tracker:${{ github.sha }}
